#version 450

// This shader should be invoked with global invocation ids
// ranging from (0, 0) to (MUSE_TOTAL_WIDTH, MUSE_TOTAL_HEIGHT).
// The input frame is modified in place.

#include "muse.h"

layout(push_constant) uniform PushConstants {
    uint dropout_mode; // 0: normal, 1: disabled, 2: highlight
};

layout(set = 0, binding = 0) buffer frame_buffer {
    float16_t frame[][MUSE_TOTAL_WIDTH];
};

layout(set = 0, binding = 1) buffer readonly dropout_data_buffer {
    uint8_t dropout_data[][MUSE_TOTAL_WIDTH];
};

void main() {
    uint row = gl_GlobalInvocationID.y;
    uint col = gl_GlobalInvocationID.x;

    // notice row and col start at 0 -- in the muse spec numbreing starts at 1
    bool is_picture_area = (row >= 46 && row < 562 || row >= 608 && row < 1124) && col >= 106;
    bool is_color_area = (row >= 42 && row < 558 || row >= 604 && row < 1120) && col >= 11 && col < 105;

    // The other shaders simply return early if row or col are outside the MUSE rectangle, but here
    // we leave also if outside the picture / color areas.  This means the col +/- indexing below is safe.
    if (!is_picture_area && !is_color_area || dropout_mode == 1)
        return;

    // We extend the detected dropouts a few pixels
    bool is_dropout = false;
    for (int i = -4; i <= 4; i++)
        if (dropout_data[row][col + i] != 0)
            is_dropout = true;

    if (is_picture_area && is_dropout) {
        if (dropout_mode == 2) {
            // set dropout pixels to red
            frame[row][col] = 120.0hf;
            frame[(row - 4) / 2 * 2][(col - 106) / 4 + 11] = 255.hf;
            frame[(row - 4) / 2 * 2 + 1][(col - 106) / 4 + 11] = 75.hf;
        } else {
            // Take the average of two preceeding and two following lines. This looks better for heavily
            // horizonally striped areas -- they will not be correct but at least the contrast is lower.
            float16_t sum = 0.hf;
            for (int i = 1; i <= 2 ; i++)
                sum += frame[row - i][col] + frame[row + i][col];
            frame[row][col] = sum / 4.hf;
        }
    }

    if (is_color_area && is_dropout) {
        if (dropout_mode == 2) {
            // set dropout pixels to green
            uint row1 = row % 2 * 2;
            uint row2 = row % 2 * 2 + 1;
            for (int i = 0; i < 4; i++) {
                frame[row1 + 4][(col - 11) * 4 + 106 + i] = 176.0hf;
                frame[row2 + 4][(col - 11) * 4 + 106 + i] = 176.0hf;
            }
            frame[row1][col] = 86.hf;
            frame[row2][col] = 75.hf;
        } else {
            // Average between the preceeding and next line (notice colors are every other line red / blue)
            frame[row][col] = 0.5hf * (frame[row - 2][col] + frame[row + 2][col]);
        }
    }
}
