#version 450

layout(local_size_x = 64) in;

layout(push_constant) uniform PushConstants {
    uint pc_data[32];
};

layout(set = 0, binding = 0) buffer readonly In { uint ssbo_data[32]; };
layout(set = 0, binding = 1) buffer writeonly Out { uint outv[]; };

void main() {
    uint x = gl_GlobalInvocationID.x;
    outv[x] = pc_data[x / 2];       // divergent index into push constants
    outv[64 + x] = ssbo_data[x / 2]; // same access pattern via SSBO (control)
}
