//
// Created by staffanu on 4/17/23.
//

#ifndef MUSECPP_MUSECONSTANTS_H
#define MUSECPP_MUSECONSTANTS_H


#define MUSE_TOTAL_HEIGHT 1125
#define MUSE_TOTAL_WIDTH 480
#define MUSE_BUF_HEIGHT 516
#define MUSE_Y_BUF_WIDTH 374
#define MUSE_C_BUF_WIDTH 94

#endif //MUSECPP_MUSECONSTANTS_H
