#version 450

// This shader should be invoked with global invocation ids
// ranging from (0, 0) to (MUSE_TOTAL_WIDTH, MUSE_TOTAL_HEIGHT).
// The input are floats, but outputs are float16_t, since all
// further processing is performed on half floats.

#include "muse.h"

layout(set = 0, binding = 0) buffer readonly frame_in_buffer {
    float16_t frame_in[][MUSE_TOTAL_WIDTH];
};

layout(set = 0, binding = 1) buffer writeonly frame_out_buffer {
    float16_t frame_out[][MUSE_TOTAL_WIDTH];
};

const float16_t min_value = 16.hf;
const float16_t max_value = 239.hf;
const float16_t value_range = 224.hf;

float16_t inverse_gamma_y(float16_t y) {
    float16_t normalized = (max(min_value, min(max_value, y)) - min_value) / value_range;
    float16_t x = (0.6hf * normalized + 0.4hf) * normalized;
    return x * value_range + min_value;
}

const float16_t a = float16_t(-48.0/11.0);
const float16_t b = float16_t(67.0/33.0);
const float16_t c = float16_t(-1.0/132.0);

float16_t inverse_gamma_c(float16_t v) {
    float16_t sign = sign(v - 128.0hf);
    float16_t v_magnitude = abs(v - 128.0hf);
    float16_t y = min(112.0hf, v_magnitude) / 112.0hf;
    float16_t x = y < 5.0hf / 72.0hf ?
        0.6hf * y :
        y < 47.hf / 33.hf / 8.hf ?
            -b / (2.0hf * a) - sqrt(b * b / (4.0hf * a * a) - (c - y) / a) :
                33.hf / 31.hf * (y - 2.hf / 33.hf);
    return 128.0hf + x * sign * 112.0hf;
}

void main() {
    uint row = gl_GlobalInvocationID.y;
    uint col = gl_GlobalInvocationID.x;

    if (row >= MUSE_TOTAL_HEIGHT || col >= MUSE_TOTAL_WIDTH)
        return;

    // Apply the de-emphasis filter for the picture area

    float16_t deemphasized;
    if ((row >= 43 && row < 47 || row >= 605 && row < 609) && (col == 1 || col >= 11 && col < 106) ||
        (row >= 47 && row < 559 || row >= 609 && row < 1121) && (col == 1 || col >= 11) ||
        (row >= 559 && row < 563 || row >= 1121 && row < 1125) && (col == 1 || col >= 107)) {
        deemphasized = 0.5hf * frame_in[row][col] +
            5.hf/32.hf * frame_in[row][col - 1] + 5.hf/32.hf * frame_in[row][col + 1] +
            1.hf/16.hf * frame_in[row][col - 2] + 1.hf/16.hf * frame_in[row][col + 2] +
            1.hf/32.hf * frame_in[row][col - 3] + 1.hf/32.hf * frame_in[row][col + 3];
    } else {
        deemphasized = frame_in[row][col];
    }

    // Apply the inverse transmission gamma (different for the color and luma parts of the picture)

    float16_t gamma_adjusted;
    if ((row >= 46 && row < 46 + MUSE_BUF_HEIGHT || (row >= 46 + 562 && row < 46 + 562 + MUSE_BUF_HEIGHT))
        && col >= 106 && col < 106 + MUSE_Y_BUF_WIDTH) {
        gamma_adjusted = inverse_gamma_y(deemphasized);
    } else if ((row >= 42 && row < 42 + MUSE_BUF_HEIGHT || (row >= 42 + 562 && row < 42 + 562 + MUSE_BUF_HEIGHT))
        && col >= 11 && col < 11 + MUSE_C_BUF_WIDTH) {
        gamma_adjusted = inverse_gamma_c(deemphasized);
    } else {
        gamma_adjusted = deemphasized;
    }

    frame_out[row][col] = gamma_adjusted;
}
