#version 450

// This shader should be invoked with global invocation ids
// ranging from (0, 0) to (MUSE_Y_BUF_WIDTH, MUSE_BUF_HEIGHT).
// The input buffer is assumed to be the complete 1125x480
// MUSE frame, and this call corrects gamma for both fields.

#define MUSE_BUF_HEIGHT 516
#define MUSE_TOTAL_WIDTH 480
#define MUSE_Y_BUF_WIDTH 374

layout (local_size_x = 4) in;
layout (local_size_y = 4) in;

layout(set = 0, binding = 0) buffer frame_data_buffer {
    float frame_data[];
};

const float min_value = 16;
const float max_value = 239;
const float value_range = 224;

float inverse_gamma(float y) {
    float normalized = (max(min_value, min(max_value, y)) - min_value) / value_range;
    float x = (0.6 * normalized + 0.4) * normalized;
    return x * value_range + min_value;
}

void main() {
    uint row = gl_GlobalInvocationID.y + 46;
    uint col = gl_GlobalInvocationID.x + 106;

    if (row >= 46 + MUSE_BUF_HEIGHT || col >= 106 + MUSE_Y_BUF_WIDTH)
        return;

    float y = frame_data[row * MUSE_TOTAL_WIDTH + col];
    frame_data[row * MUSE_TOTAL_WIDTH + col] = inverse_gamma(y);

    y = frame_data[(row + 562) * MUSE_TOTAL_WIDTH + col];
    frame_data[(row + 562) * MUSE_TOTAL_WIDTH + col] = inverse_gamma(y);
}
