#version 450

// This shader should be invoked with global invocation ids
// ranging from (0, 0) to (MUSE_C_BUF_WIDTH, MUSE_BUF_HEIGHT).
// The input buffer is assumed to be the complete 1125x480
// MUSE frame, and this call corrects gamma for both fields.

#define MUSE_BUF_HEIGHT 516
#define MUSE_TOTAL_WIDTH 480
#define MUSE_C_BUF_WIDTH 94

layout (local_size_x = 4) in;
layout (local_size_y = 4) in;

layout(set = 0, binding = 0) buffer frame_data_buffer {
    float frame_data[];
};

const float a = -48.0/11.0;
const float b = 67.0/33.0;
const float c = -1.0/132.0;

float inverse_gamma(float v) {
    float sign = v < 128 ? -1.0 : 1.0;
    float v_magnitude = abs(v - 128.0);
    float y = min(112.0, v_magnitude) / 112.0;
    float x = y < 5.0 / 72.0 ?
        0.6 * y :
        y < 47 / 33 / 8 ?
            -b / (2 * a) - sqrt(b * b / (4 * a * a) - (c - y) / a) :
            33 / 31 * (y - 2 / 33);
    return 128 + x * sign * 112;
}

void main() {
    uint row = gl_GlobalInvocationID.y + 42;
    uint col = gl_GlobalInvocationID.x + 11;

    if (row >= 42 + MUSE_BUF_HEIGHT || col >= 11 + MUSE_C_BUF_WIDTH)
        return;

    float y = frame_data[row * MUSE_TOTAL_WIDTH + col];
    frame_data[row * MUSE_TOTAL_WIDTH + col] = inverse_gamma(y);

    y = frame_data[(row + 562) * MUSE_TOTAL_WIDTH + col];
    frame_data[(row + 562) * MUSE_TOTAL_WIDTH + col] = inverse_gamma(y);
}
