#version 450

#include "muse.h"

// This shader should be invoked with global invocation ids
// from (0, 0) to (MUSE_Y_BUF_WIDTH * 3, MUSE_BUF_HEIGHT * 2)

layout(push_constant) uniform PushConstants {
    // both set to 1 makes no sense
    uint force_field_only;
    uint force_inter_frame_only;
    uint output_yuv;
};

layout(set = 0, binding = 0) buffer readonly field_Y_buffer {
    float16_t field_y[];
};

layout(set = 0, binding = 1) buffer readonly field_r_buffer {
    float16_t field_r[];
};

layout(set = 0, binding = 2) buffer readonly field_b_buffer {
    float16_t field_b[];
};

layout(set = 0, binding = 3) buffer readonly inter_frame_Y_buffer {
    float16_t inter_frame_y[];
};

layout(set = 0, binding = 4) buffer readonly inter_frame_r_buffer {
    float16_t inter_frame_r[];
};

layout(set = 0, binding = 5) buffer readonly inter_frame_b_buffer {
    float16_t inter_frame_b[];
};

layout(set = 0, binding = 6) buffer readonly movement_buffer {
    float16_t movement_data[][MUSE_Y_BUF_WIDTH * 3];
};

layout(set = 0, binding = 7, rgba32f) uniform writeonly image2D frame_out_image;

layout(set = 0, binding = 8) buffer writeonly frame_out_y_buffer {
    uint16_t frame_out_y[][MUSE_Y_BUF_WIDTH * 3];
};

layout(set = 0, binding = 9) buffer writeonly frame_out_u_buffer {
    uint16_t frame_out_u[][MUSE_Y_BUF_WIDTH * 3 / 2];
};

layout(set = 0, binding = 10) buffer writeonly frame_out_v_buffer {
    uint16_t frame_out_v[][MUSE_Y_BUF_WIDTH * 3 / 2];
};


void main() {
    uint row = gl_GlobalInvocationID.y;
    uint col = gl_GlobalInvocationID.x;

    if (row >= MUSE_BUF_HEIGHT * 2 || col >= MUSE_Y_BUF_WIDTH * 3)
        return;

    float16_t YM_field = field_y[row * MUSE_Y_BUF_WIDTH * 3 + col];
    float16_t RmYM_field = field_r[(row / 2) * MUSE_Y_BUF_WIDTH + col / 3] - 128.0hf;
    float16_t BmYM_field = field_b[(row / 2) * MUSE_Y_BUF_WIDTH + col / 3] - 128.0hf;
    float16_t YM_inter_frame = inter_frame_y[row * MUSE_Y_BUF_WIDTH * 3 + col];
    float16_t RmYM_inter_frame = inter_frame_r[(row / 2) * MUSE_Y_BUF_WIDTH + col / 3] - 128.0hf;
    float16_t BmYM_inter_frame = inter_frame_b[(row / 2) * MUSE_Y_BUF_WIDTH + col / 3] - 128.0hf;

    float16_t movement = force_field_only != 0 ?
        1.0hf : force_inter_frame_only != 0 ?
            0.0hf : movement_data[row][col];

    float16_t YM = YM_field * movement + YM_inter_frame * (1.0hf - movement);
    float16_t BmYM = BmYM_field * movement + BmYM_inter_frame * (1.0hf - movement);
    float16_t RmYM = RmYM_field * movement + RmYM_inter_frame * (1.0hf - movement);

//    float16_t YM = movement_data[row][col] * 255.hf;
//    float16_t BmYM = 0.hf;
//    float16_t RmYM = 0.hf;

    float16_t min_value = 16.hf;
    float16_t range = 235.hf - min_value;
    float16_t g = clamp((YM - BmYM / 4.0hf - RmYM / 2.0hf - min_value) / range, 0.hf, 1.hf);
    float16_t b = clamp((YM + BmYM + BmYM / 4.0hf - min_value) / range, 0.hf, 1.hf);
    float16_t r = clamp((YM + RmYM - min_value) / range, 0.hf, 1.hf);

    r = pow(r, 2.2hf);
    g = pow(g, 2.2hf);
    b = pow(b, 2.2hf);

    imageStore(frame_out_image, ivec2(col, row), vec4(float(r), float(g), float(b), 1.f));

    if (output_yuv != 0) {
        frame_out_y[row][col] = uint16_t(clamp(YM * 256.hf, 0.hf, 65535.hf));
        if ((row & 1) == 0 && (col & 1) == 0) {
            frame_out_u[row / 2][col / 2] = uint16_t(clamp((BmYM + 128.hf) * 256.hf, 0.hf, 65535.hf));
            frame_out_v[row / 2][col / 2] = uint16_t(clamp((RmYM + 128.hf) * 256.hf, 0.hf, 65535.hf));
        }
    }
}
