#version 450

#include "muse.h"

// This shader should be invoked with global invocation ids
// from (0, 0) to (MUSE_Y_BUF_WIDTH * 3, MUSE_BUF_HEIGHT * 2)

layout(push_constant) uniform PushConstants {
    // both set to 1 makes no sense
    uint force_field_only;
    uint force_inter_frame_only;
};

layout(set = 0, binding = 0) buffer field_Y_buffer {
    float field_y[];
};

layout(set = 0, binding = 1) buffer field_r_buffer {
    float field_r[];
};

layout(set = 0, binding = 2) buffer field_b_buffer {
    float field_b[];
};

layout(set = 0, binding = 3) buffer inter_frame_Y_buffer {
    float inter_frame_y[];
};

layout(set = 0, binding = 4) buffer inter_frame_r_buffer {
    float inter_frame_r[];
};

layout(set = 0, binding = 5) buffer inter_frame_b_buffer {
    float inter_frame_b[];
};

layout(set = 0, binding = 6) buffer movement_buffer {
    float movement_data[];
};

layout(set = 0, binding = 7) buffer frame_out_buffer {
    uint frame_out[];
};

//layout(set = 0, binding = 8, rgba32ui) uniform writeonly uimage2D frame_out_image;

void main() {
    uint row = gl_GlobalInvocationID.y;
    uint col = gl_GlobalInvocationID.x;

    if (row >= MUSE_BUF_HEIGHT * 2 || col >= MUSE_Y_BUF_WIDTH * 3)
        return;

    float YM_field = field_y[row * MUSE_Y_BUF_WIDTH * 3 + col];
    float RmYM_field = field_r[(row / 2) * MUSE_Y_BUF_WIDTH + col / 3] - 128.0f;
    float BmYM_field = field_b[(row / 2) * MUSE_Y_BUF_WIDTH + col / 3] - 128.0f;
    float YM_inter_frame = inter_frame_y[row * MUSE_Y_BUF_WIDTH * 3 + col];
    float RmYM_inter_frame = inter_frame_r[(row / 2) * MUSE_Y_BUF_WIDTH + col / 3] - 128.0f;
    float BmYM_inter_frame = inter_frame_b[(row / 2) * MUSE_Y_BUF_WIDTH + col / 3] - 128.0f;

    float movement = force_field_only != 0 ?
        1.0f : force_inter_frame_only != 0 ?
            0.0f : movement_data[row * MUSE_Y_BUF_WIDTH * 3 + col];

    float YM = YM_field * movement + YM_inter_frame * (1 - movement);
    float BmYM = BmYM_field * movement + BmYM_inter_frame * (1 - movement);
    float RmYM = RmYM_field * movement + RmYM_inter_frame * (1 - movement);

    int g = clamp(int(YM - BmYM / 4 - RmYM / 2), 0, 255);
    int b = clamp(int(YM + BmYM + BmYM / 4), 0, 255);
    int r = clamp(int(YM + RmYM), 0, 255);

    frame_out[row * MUSE_Y_BUF_WIDTH * 3 + col] = (0xff << 24) | (r << 16) | (g << 8) | (b);
    //imageStore(frame_out_image, ivec2(row, col), uvec4(r, g, b, 255));
}
