#version 450

// This shader should be invoked with global invocation ids
// from (0, 0) to (source_width * upsmple_factor / downsample_factor, source_height)

layout(push_constant) uniform PushConstants {
    uint filter_size;
    uint upsample_factor;
    uint downsample_factor;
    uint source_height;
    uint source_width;
    uint dest_start_row;
    uint dest_row_step_size;
    uint dest_start_col;
    uint dest_col_step_size;
    uint multiplier;
};

layout (local_size_x = 4) in;
layout (local_size_y = 4) in;

layout(set = 0, binding = 0) buffer filter_buffer {
    float fir_filter[];
};

layout(set = 0, binding = 1) buffer source_buffer {
    float source[];
};

layout(set = 0, binding = 2) buffer dest_buffer {
    float dest[];
};

// Convert to upsample_factor/downsample_factor of the input sample rate by inserting two zeros
// between samples to up-sample, low-pass filter, and then select every downsample_factor sample.
// We do not represent the up-sampled signal explicitly, and also do not represent the entire
// filter output but only the values we actually use.

// The dest_row_step_size and dest_col_step_size parameters are "applied" after filtering so the
// invocation indices tell for what coordinated in the original filter output is computed.

void main() {
    uint source_row = gl_GlobalInvocationID.y;
    uint dest_col_filter_out = gl_GlobalInvocationID.x;
    uint dest_width_filter_out = source_width * upsample_factor / downsample_factor;

    if (source_row >= source_height || dest_col_filter_out >= dest_width_filter_out)
        return;

    uint dest_row = dest_start_row + source_row * dest_row_step_size;
    uint dest_width = dest_width_filter_out * dest_col_step_size;
    uint dest_col = dest_start_col + dest_col_filter_out * dest_col_step_size;

    int N = int(filter_size) / 2;
    int hiFreqIx = int(dest_col_filter_out * downsample_factor /* + dest_start_col * 2 */);
    float s = 0;
    for (int l = (hiFreqIx - N + int(upsample_factor) - 1) / int(upsample_factor); l <= (hiFreqIx + N) / int(upsample_factor); l++) {
        float v = l >= 0 && l < source_width ? source[source_row * source_width + l] : 128;
        s += v * fir_filter[upsample_factor * l - hiFreqIx + N];
    }
    dest[dest_row * dest_width + dest_col] = clamp(s * upsample_factor * multiplier, 0, 255);
}
