#version 450

// This shader should be invoked with global invocation ids
// ranging from (0, 0) to (MUSE_TOTAL_WIDTH, MUSE_TOTAL_HEIGHT).
// The input is an array of uint, but it consists of 16 bit shorts,
// So we do some bit manipulation to extract the correct part.

#include "muse.h"

layout(push_constant) uniform PushConstants {
    float eq1_f;
    float eq2_f;
};

layout(set = 0, binding = 0) buffer readonly frame_in_buffer {
    uint frame_in[];
};

layout(set = 0, binding = 1) buffer writeonly frame_out_buffer {
    float16_t frame_out[];
};

//#define SWAP_BYTES(a) (((a & 0xffu) << 8) | ((a & 0xff00u) >> 8))
#define SWAP_BYTES(a) (a)

const float16_t min_value = 16.hf;
const float16_t max_value = 239.hf;
const float16_t value_range = 224.hf;

float16_t inverse_gamma_y(float16_t y) {
    float16_t normalized = (max(min_value, min(max_value, y)) - min_value) / value_range;
    float16_t x = (0.6hf * normalized + 0.4hf) * normalized;
    return x * value_range + min_value;
}

const float16_t a = float16_t(-48.0/11.0);
const float16_t b = float16_t(67.0/33.0);
const float16_t c = float16_t(-1.0/132.0);

float16_t inverse_gamma_c(float16_t v) {
    float16_t sign = sign(v - 128.0hf);
    float16_t v_magnitude = abs(v - 128.0hf);
    float16_t y = min(112.0hf, v_magnitude) / 112.0hf;
    float16_t x = y < 5.0hf / 72.0hf ?
        0.6hf * y :
        y < 47.hf / 33.hf / 8.hf ?
            -b / (2.0hf * a) - sqrt(b * b / (4.0hf * a * a) - (c - y) / a) :
                33.hf / 31.hf * (y - 2.hf / 33.hf);
    return 128.0hf + x * sign * 112.0hf;
}

void main() {
    uint row = gl_GlobalInvocationID.y;
    uint col = gl_GlobalInvocationID.x;

    if (row >= MUSE_TOTAL_HEIGHT || col >= MUSE_TOTAL_WIDTH)
        return;

    uint uint32_value = frame_in[row * MUSE_TOTAL_WIDTH / 2 + col / 2];
    uint uint16_value = col % 2 == 1 ?
        SWAP_BYTES(uint32_value >> 16) :
        SWAP_BYTES(uint32_value & 0xffffu);

    float16_t eq1 = float16_t(eq1_f);
    float16_t eq2 = float16_t(eq2_f);
    float16_t equalized = clamp((float16_t(uint16_value) / MUSE_INPUT_MULT - eq2) / eq1, 0.0hf, 255.0hf);

    if ((row >= 46 && row < 46 + MUSE_BUF_HEIGHT || (row >= 46 + 562 && row < 46 + 562 + MUSE_BUF_HEIGHT))
        && col >= 106 && col < 106 + MUSE_Y_BUF_WIDTH) {
        equalized = inverse_gamma_y(equalized);
    } else if ((row >= 42 && row < 42 + MUSE_BUF_HEIGHT || (row >= 42 + 562 && row < 42 + 562 + MUSE_BUF_HEIGHT))
        && col >= 11 && col < 11 + MUSE_C_BUF_WIDTH) {
        equalized = inverse_gamma_c(equalized);
    }

    frame_out[row * MUSE_TOTAL_WIDTH + col] = equalized;
}
