#version 450

#extension GL_EXT_shader_atomic_float: enable

// This shader should be invoked with global invocation ids
// from (0, 0) to (source_width * 3 / 2, source_height)

layout(push_constant) uniform PushConstants {
    uint filter_size;
    uint source_height;
    uint source_width;
    uint dest_start_row;
    uint dest_row_step_size;
};

layout (local_size_x = 4) in;
layout (local_size_y = 4) in;

layout(set = 0, binding = 0) buffer filter_buffer {
    float fir_filter[];
};

layout(set = 0, binding = 1) buffer source_buffer {
    float source[];
};

layout(set = 0, binding = 2) buffer dest_buffer {
    float dest[];
};

// Convert to 3/2 of the input sample rate by inserting two zeros between samples to up-sample 3x,
// low-pass filter at 0.5 times the new Nyquist rate and then select every 2nd sample

// We do not represent the up-sampled signal explicitly, and also do not represent the entire filter output
// since we only need every 2nd sample

void main() {
    uint source_row = gl_GlobalInvocationID.y;
    uint dest_col = gl_GlobalInvocationID.x;
    uint dest_row = dest_start_row + source_row * dest_row_step_size;
    uint dest_width = source_width * 3 / 2;

    if (source_row >= source_height || dest_col >= dest_width)
        return;

    int N = int(filter_size) / 2;
    int hiFreqIx = int(dest_col) * 2;
    float s = 0;
    for (int l = (hiFreqIx - N + 2) / 3; l <= (hiFreqIx + N) / 3; l++) {
        float v = l >= 0 && l < source_width ? source[source_row * source_width + l] : 128;
        s += v * fir_filter[3 * l - hiFreqIx + N];
    }
    dest[dest_row * dest_width + dest_col] = clamp(s * 3, 0, 255);
}
