#version 450

// This shader should be invoked with global invocation ids
// ranging from (0, 0) to (MUSE_Y_BUF_WIDTH, MUSE_BUF_HEIGHT).
// The input buffer is assumed to be the complete 1125x480
// MUSE frame.

#include "muse.h"

layout(push_constant) uniform PushConstants {
    uint field_parity;
    uint frame_phase_y;
    uint zero_non_copied_entries;
};

layout(set = 0, binding = 0) buffer readonly frame_data_buffer {
    float16_t frame_data[][MUSE_TOTAL_WIDTH];
};

layout(set = 0, binding = 1) buffer writeonly output_data_buffer {
    float16_t output_data[][ MUSE_Y_BUF_WIDTH * 2];
};

void main() {
    uint row = gl_GlobalInvocationID.y;
    uint col = gl_GlobalInvocationID.x;

    if (row >= MUSE_BUF_HEIGHT || col >= MUSE_Y_BUF_WIDTH)
        return;

    uint v_offset = field_parity == 0 ? 46 : 608;
    uint phase = (frame_phase_y + row + 1) % 2; // notice row is even when line no is odd (row 0 is really line 47/609)

    float16_t v = frame_data[(row + v_offset)][col + 106];

    output_data[row][col * 2 + phase] = v;
    if (zero_non_copied_entries != 0)
        output_data[row][col * 2 + 1 - phase] = 0.hf;
}
