#version 450

#define MUSE_BUF_HEIGHT 516
#define MUSE_TOTAL_WIDTH 480
#define MUSE_Y_BUF_WIDTH 374
#define MUSE_C_BUF_WIDTH 94
#define MUSE_C_OFFSET 11

// This shader should be invoked with global invocation ids
// from (0, 0) to (MUSE_Y_BUF_WIDTH, MUSE_BUF_HEIGHT)

layout(push_constant) uniform PushConstants {
    uint frame_phase_c;
    uint field_parity;
};

layout (local_size_x = 4) in;
layout (local_size_y = 4) in;

layout(set = 0, binding = 0) buffer input_frame_buffer {
    float input_frame[];
};

layout(set = 0, binding = 1) buffer r_data_buffer {
    float r_data[];
};

layout(set = 0, binding = 2) buffer b_data_buffer {
    float b_data[];
};

void main() {
    uint row = gl_GlobalInvocationID.y;
    uint col = gl_GlobalInvocationID.x;

    if (row >= MUSE_BUF_HEIGHT || col >= MUSE_Y_BUF_WIDTH)
        return;

    uint line = row + 43 + field_parity * 562; // starts at 1
    uint offset = (frame_phase_c + line + 1) % 2 * 2 + field_parity;

    if (col % 4 == offset) {
        float v = input_frame[(line - 1) * MUSE_TOTAL_WIDTH + MUSE_C_OFFSET + col / 4];

        bool is_red = line % 2 == 1;
        if (is_red) {
            r_data[row * MUSE_Y_BUF_WIDTH + col] = v;
            b_data[row * MUSE_Y_BUF_WIDTH + col] = 0;
        } else {
            r_data[row * MUSE_Y_BUF_WIDTH + col] = 0;
            b_data[row * MUSE_Y_BUF_WIDTH + col] = v;
        }
    } else {
        r_data[row * MUSE_Y_BUF_WIDTH + col] = 0;
        b_data[row * MUSE_Y_BUF_WIDTH + col] = 0;
    }
}
