#version 450

// This shader should be invoked with global invocation ids
// from (0, 0) to (MUSE_Y_BUF_WIDTH, MUSE_BUF_HEIGHT)

#include "muse.h"

layout(push_constant) uniform PushConstants {
    uint frame_phase_c;
    uint field_parity;
    uint zero_non_sample_points;
};

layout(set = 0, binding = 0) buffer input_frame_buffer {
    float16_t input_frame[];
};

layout(set = 0, binding = 1) buffer r_data_buffer {
    float16_t r_data[];
};

layout(set = 0, binding = 2) buffer b_data_buffer {
    float16_t b_data[];
};

void main() {
    uint row = gl_GlobalInvocationID.y;
    uint col = gl_GlobalInvocationID.x;

    if (row >= MUSE_BUF_HEIGHT || col >= MUSE_Y_BUF_WIDTH)
        return;

    uint line = row + 43 + field_parity * 562; // starts at 1
    uint line_div_2_odd = (line / 2) % 2;
    uint offset = (line_div_2_odd == frame_phase_c ? 0 : 2) + field_parity;

    if (zero_non_sample_points != 0) {
        r_data[row * MUSE_Y_BUF_WIDTH + col] = 0.hf;
        b_data[row * MUSE_Y_BUF_WIDTH + col] = 0.hf;
    }

    if (col % 4 == offset) {
        float16_t v = input_frame[(line - 1) * MUSE_TOTAL_WIDTH + MUSE_C_OFFSET + col / 4];

        bool is_red = line % 2 == 1;
        if (is_red) {
            r_data[row * MUSE_Y_BUF_WIDTH + col] = v;
        } else {
            b_data[row * MUSE_Y_BUF_WIDTH + col] = v;
        }
    }
}
