#version 450

// This shader should be invoked with global invocation ids
// from (0, 0) to (width, height / 2)

#include "muse.h"

layout(push_constant) uniform PushConstants {
    uint height;
    uint width;
    uint parity;
};

layout(set = 0, binding = 0) buffer frame_buffer {
    float16_t frame[];
};

// probably not the best interpolation of missing lines but looks more or less ok

void main() {
    uint row = gl_GlobalInvocationID.y * 2 + parity;
    uint col = gl_GlobalInvocationID.x;

    if (row >= height || col >= width)
        return;

    uint row_above = row == 0 ? 1 : row - 1;
    uint row_below = row == height - 1 ? height - 2 : row + 1;
    float16_t s = (frame[row_above * width + col] + frame[row_below * width + col]) / 2.hf;

    frame[row * width + col] = clamp(s, 0.hf, 255.hf);
}
