#version 450

// This shader should be invoked with global invocation ids
// from (0, 0) to (image_width - 1, image_height - 1)

#include "muse.h"

layout(push_constant) uniform PushConstants {
    float filter_height_f;
    float filter_width_f;
    float image_height_f;
    float image_width_f;
    float multiplier_f;
};

layout(set = 0, binding = 0) buffer readonly image_filter_buffer {
    float16_t image_filter[];
};

layout(set = 0, binding = 1) buffer readonly source_buffer {
    float16_t source[];
};

layout(set = 0, binding = 2) buffer writeonly dest_buffer {
    float16_t dest[];
};

#define MAX_FILTER_SIZE 64 // same as workgroup size
shared float16_t shared_filter[MAX_FILTER_SIZE];

void main() {
    int row = int(gl_GlobalInvocationID.y);
    int col = int(gl_GlobalInvocationID.x);
    int image_height = int(image_height_f);
    int image_width = int(image_width_f);
    int filter_height = int(filter_height_f);
    int filter_width = int(filter_width_f);
    float16_t multiplier = float16_t(multiplier_f);

    // This converts the local index to a one-dimensional index!
    uint local_ix = gl_LocalInvocationID.x + gl_WorkGroupSize.x * gl_LocalInvocationID.y;
    if (local_ix < filter_width * filter_height)
        shared_filter[local_ix] = image_filter[local_ix];

    barrier();

    if (row >= image_height || col >= image_width)
        return;

    int H = filter_height / 2;
    int W = filter_width / 2;

    float16_t s = 0.hf;
    for (int i = -H; i <= H; i++) {
        int read_row = row + i;
        for (int j = -W; j <= W; j ++) {
            int read_col = col + j;

            int rc = read_col < 0 ? -read_col : read_col >= image_width ? image_width - 1 - (read_col - image_width - 1) : read_col;
            // This filter is only used for the color area.  Outside the bottom, due to the geometry of the color pixels, it looks better to
            // repeat the last four rows than does reflection.
            int rr = read_row < 0 ? -read_row : read_row >= image_height ? image_height - 4 + (read_row - image_height) % 4 : read_row;

            float16_t v = source[rr * image_width + rc];
            s += v * shared_filter[(i + H) * filter_width + j + W];
        }
    }
    dest[row * image_width + col] = clamp(s * multiplier, 0.hf, 255.hf);
}
