#version 450

// This shader should be invoked with global invocation ids
// from (0, 0) until (MUSE_Y_BUF_WIDTH, MUSE_BUF_HEIGHT).
//
// Filters the chroma information in place.
// The is_red flag tells whether to filter the R och B color information -- the difference is
// that the first red signal is on rows 0 and 1, while the first blue signal is on rows 2 and 3.
// The phase input says whether the first two rows of information are aligned to the left (1)
// or top the right (0).
// If filter_stage is 0, the rows containing color informatation (2 out of 4 rows) are filtered
// horizontally.  If filter_stage is 1, the other two rows are filled in.

#include "muse.h"

// With this filter we could clearly simplify the code...
#define HORIZ_FILTER_SIZE 3
float16_t filter_coeffs[HORIZ_FILTER_SIZE] = { 0.25hf, 0.5hf, 0.25hf };

layout(push_constant) uniform PushConstants {
    uint is_red;
    uint filter_stage;
};

layout(set = 0, binding = 0) buffer c_buffer {
    float16_t c_data[MUSE_BUF_HEIGHT * 2][MUSE_Y_BUF_WIDTH];
};

void main() {
    uint row = gl_GlobalInvocationID.y;
    uint col = gl_GlobalInvocationID.x;

    if (row >= MUSE_BUF_HEIGHT || col >= MUSE_Y_BUF_WIDTH)
        return;

    switch (filter_stage) {
        case 0: // Fill in the missing samples in the rows that do have samples (rows 0, 1 for red, 2, 3 for blue, and so on) by filtering horizontally
        {
            uint y = row / 2 * 4 + (row & 1u) + (is_red != 0 ? 0 : 2);
            uint known_pixels_phase = 1 - (row & 1u);
            if (col % 2 != known_pixels_phase) {
                int W = HORIZ_FILTER_SIZE / 2;
                int W_odd =  (W - 1) / 2 * 2 + 1; // rounded down to odd value
                float16_t s = 0.hf;
                for (int i = -W_odd; i <= W_odd; i += 2) {
                    float16_t v;
                    if (col + i >= 0 && col + i < MUSE_Y_BUF_WIDTH)
                        v = c_data[y][col + i];
                    else
                        v = 128.hf;
                    s += v * filter_coeffs[W + i];
                }
                c_data[y][col] = s * 2.hf; // * 2 since we need to amplify the signal to compensate for missing samples
            }
        }
        break;
        case 1: // Fill in the missing samples in the rows without samples (rows 0, 1 for blue, 2, 3 for red, and so on) by filtering vertically
        { // TODO: implement a real filter -- now we just copy!
            uint y = row / 2 * 4 + (row & 1u) + (is_red != 0 ? 2 : 0);
            uint source_y;
            if ((row & 1u) == 0) {
                source_y = y == 0 ? 2 : y - 1;
            } else {
                source_y = y == 2 * MUSE_BUF_HEIGHT - 1 ? MUSE_BUF_HEIGHT - 3 : y + 1;
            }
            c_data[y][col] = c_data[source_y][col];
        }
        break;
    }
}
