#version 450

// This shader should be invoked with global invocation ids
// from (0, 0) to (frame_buffer_width / 2, frame_buffer_height)

#include "muse.h"

layout(push_constant) uniform PushConstants {
    uint filter_height;
    uint filter_width;
    uint frame_buffer_height;
    uint frame_buffer_width;
    uint phase;
};

layout(set = 0, binding = 0) buffer readonly filter_input {
    float16_t diamond_filter[];
};

layout(set = 0, binding = 1) buffer framebuffer_inout {
    float16_t frame_buffer[];
};

#define MAX_FILTER_SIZE 64 // same as workgroup size
shared float16_t shared_filter[MAX_FILTER_SIZE];

void main() {
    // This converts the local index to a one-dimensional index
    uint local_ix = gl_LocalInvocationID.x + gl_WorkGroupSize.x * gl_LocalInvocationID.y;
    if (local_ix < filter_width * filter_height)
            shared_filter[local_ix] = diamond_filter[local_ix];

    barrier();

    uint row = gl_GlobalInvocationID.y;
    uint invocation_x = gl_GlobalInvocationID.x;
    uint col = (phase + row) % 2 + invocation_x * 2;

    if (row >= frame_buffer_height || col >= frame_buffer_width)
        return;

    uint H = filter_height / 2;
    uint W = filter_width / 2;
    uint W_odd =  (W - 1) / 2 * 2 + 1;// rounded down to odd value

    float16_t s = 0.hf;
    int i_start = -int(min(H, row));
    int i_max = int(min(H, frame_buffer_height - row - 1));
    for (int i = i_start; i <= i_max; i++) {
        int j_start = i % 2 == 0 ? -int(W_odd) : -int(W);
        int j_max = int(min(W, frame_buffer_width - col - 1));
        for (int j = j_start; j <= j_max; j += 2)
            if (col + j >= 0)
                s += frame_buffer[(row + i) * frame_buffer_width + col + j] *
                    shared_filter[(i + H) * filter_width + j + W];
    }
    frame_buffer[row * frame_buffer_width + col] = clamp(s * 2.hf, 0.hf, 255.hf);
}
