#version 450

#include "muse.h"

// This shader should be invoked with global invocation ids
// from (0, 0) until (NTSC_Y_BUF_WIDTH, NTSC_FIELD_HEIGHT * 2)

layout(push_constant) uniform PushConstants {
    // both set to 1 makes no sense
    uint force_field_only;
    uint force_inter_frame_only;
    int field_parity; // Parity for the field buffer: 0 for first field (lower)(?), 1 for second (upper)(?)
    uint output_yuv;
};

layout(set = 0, binding = 0) buffer readonly restrict field_Y_buffer {
    float16_t field_y[][NTSC_Y_BUF_WIDTH];
};

layout(set = 0, binding = 1) buffer readonly restrict field_r_buffer {
    float16_t field_r[][NTSC_Y_BUF_WIDTH / 2];
};

layout(set = 0, binding = 2) buffer readonly restrict field_b_buffer {
    float16_t field_b[][NTSC_Y_BUF_WIDTH / 2];
};

layout(set = 0, binding = 3) buffer readonly restrict inter_frame_Y_buffer {
    float16_t inter_frame_y[][NTSC_Y_BUF_WIDTH];
};

layout(set = 0, binding = 4) buffer readonly restrict inter_frame_r_buffer {
    float16_t inter_frame_r[][NTSC_Y_BUF_WIDTH / 2];
};

layout(set = 0, binding = 5) buffer readonly restrict inter_frame_b_buffer {
    float16_t inter_frame_b[][NTSC_Y_BUF_WIDTH / 2];
};

layout(set = 0, binding = 6) buffer readonly restrict movement_buffer {
    float16_t movement_data[][NTSC_Y_BUF_WIDTH];
};

layout(set = 0, binding = 7, rgba32f) uniform writeonly image2D frame_out_image;

layout(set = 0, binding = 8) buffer writeonly frame_out_y_buffer {
    uint16_t frame_out_y[][NTSC_Y_BUF_WIDTH];
};

layout(set = 0, binding = 9) buffer writeonly frame_out_u_buffer {
    uint16_t frame_out_u[][NTSC_Y_BUF_WIDTH / 2];
};

layout(set = 0, binding = 10) buffer writeonly frame_out_v_buffer {
    uint16_t frame_out_v[][NTSC_Y_BUF_WIDTH / 2];
};

void main() {
    uint row = gl_GlobalInvocationID.y;
    uint col = gl_GlobalInvocationID.x;

    if (row >= NTSC_FIELD_HEIGHT * 2 || col >= NTSC_Y_BUF_WIDTH)
        return;

    float16_t v;
    if (force_field_only != 0) {
        v = field_y[(row + 1 - field_parity) / 2][col];
    } else if (force_inter_frame_only != 0) {
        v = inter_frame_y[row][col];
    } else {
        v = field_y[(row + 1 - field_parity) / 2][col]; // FIXME: combine!
    }
    v = clamp(v, 0.hf, 1.hf);

    imageStore(frame_out_image, ivec2(col, row), vec4(float(v), float(v), float(v), 1.f));

    if (output_yuv != 0) {
    }
}
